### ISSUE TITLE
Use without relay?

### ISSUE THREAD

**Issue by nietzscheson** [0soft/graphene-django-plus#29] opened 2021-06-17 15:10 UTC
Can I use this package without relay interface?

**Comment by bellini666** [comment] 2021-06-17 15:23
Hey @nietzscheson .

This package right now is unfortunately very tied to relay (at least the mutations part is). There's an open issue here (https://github.com/0soft/graphene-django-plus/issues/1) regarding making relay optional, but I don't have the time to do that right now.

But feel free to try to make that happen and open a PR for the project, I'll gladly review it and integrate it if it looks good!

ps. I'm closing this issue as duplicate of that issue that I mentioned above

**Closed by bellini666** 2021-06-17 15:23 UTC

**Comment by nietzscheson** [comment] 2021-06-17 16:59
I'm trying!
